# Generated by Django 6.0.2 on 2026-02-06 21:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text="User's question")),
                ('answer', models.TextField(help_text="AI's response")),
                ('user_age_at_time', models.PositiveIntegerField(blank=True, null=True)),
                ('pregnancy_weeks_at_time', models.PositiveIntegerField(blank=True, null=True)),
                ('helpful', models.BooleanField(blank=True, help_text='Was this response helpful?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, help_text='Group chats by session', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDisclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer_text', models.TextField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclaimers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Disclaimer',
                'verbose_name_plural': 'Medical Disclaimers',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age in years', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], default='N', max_length=1)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('profession', models.CharField(blank=True, help_text='Occupation', max_length=100)),
                ('location', models.CharField(blank=True, help_text='City, State', max_length=100)),
                ('pregnancy_status', models.CharField(choices=[('not_pregnant', 'Not Pregnant'), ('pregnant', 'Pregnant'), ('postpartum', 'Postpartum'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20)),
                ('pregnancy_weeks', models.PositiveIntegerField(blank=True, help_text='Current week of pregnancy (0-42)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(42)])),
                ('due_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/default.png', upload_to='profile_pictures/')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=5)),
                ('dark_mode_enabled', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('medical_disclaimer_accepted', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
