# Generated by Django 6.0.2 on 2026-02-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, choices=[('avatar1', 'Avatar 1'), ('avatar2', 'Avatar 2'), ('avatar3', 'Avatar 3')], max_length=20, null=True),
        ),
    ]
