# Generated by Django 6.0.2 on 2026-02-09 22:31

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('checkup', 'Regular Checkup'), ('ultrasound', 'Ultrasound/Scan'), ('blood_test', 'Blood Test'), ('vaccination', 'Vaccination'), ('specialist', 'Specialist Consultation'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Post-appointment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='UltrasoundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_weight_grams', models.PositiveIntegerField(blank=True, help_text='Estimated baby weight in grams', null=True)),
                ('baby_length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Baby length in cm', max_digits=5, null=True)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heart_rate_bpm', models.PositiveIntegerField(blank=True, help_text="Baby's heart rate (beats per minute)", null=True)),
                ('baby_position', models.CharField(blank=True, help_text='e.g., Head down, Breech', max_length=50)),
                ('gender_revealed', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl'), ('not_revealed', 'Not Revealed')], max_length=20)),
                ('amniotic_fluid_level', models.CharField(blank=True, max_length=50)),
                ('placenta_position', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Ultrasound Detail',
                'verbose_name_plural': 'Ultrasound Details',
            },
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-record_date', '-created_at'], 'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(blank=True, help_text='Notes about this record'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.CharField(blank=True, help_text='Doctor/Clinic name', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Star important documents'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='key_findings',
            field=models.TextField(blank=True, help_text="Important notes or results (e.g., 'Baby weight: 2.5kg, Heart rate: Normal')"),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pregnancy_week',
            field=models.PositiveIntegerField(blank=True, help_text='Specific week if known', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(42)]),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateField(default=datetime.date.today, help_text='Date of test/scan/visit'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('ultrasound', 'Ultrasound/Sonography'), ('blood_test', 'Blood Test Results'), ('urine_test', 'Urine Test Results'), ('scan', 'Medical Scan (CT/MRI)'), ('prescription', 'Prescription'), ('report', 'Medical Report'), ('vaccination', 'Vaccination Record'), ('other', 'Other Document')], default='other', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separated by commas (e.g., diabetes, blood pressure)', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated for images', null=True, upload_to='medical_records/thumbnails/'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='document',
            field=models.FileField(help_text='Upload PDF, image, or document (max 10MB)', upload_to='medical_records/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='title',
            field=models.CharField(help_text='e.g., 20-Week Anatomy Scan, Blood Test Week 12', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='trimester',
            field=models.PositiveIntegerField(choices=[(1, 'First Trimester (Weeks 1-13)'), (2, 'Second Trimester (Weeks 14-26)'), (3, 'Third Trimester (Weeks 27-40)'), (0, 'Pre-Pregnancy/Other')], default=1, help_text='Which trimester was this from?'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['user', '-record_date'], name='maternal_he_user_id_dbc3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['trimester', '-record_date'], name='maternal_he_trimest_158d91_idx'),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='related_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='maternal_health.medicalrecord'),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ultrasoundimage',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_details', to='maternal_health.medicalrecord'),
        ),
    ]
