# Generated by Django 6.0.2 on 2026-02-06 21:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('motor', 'Motor Skills'), ('social', 'Social & Emotional'), ('language', 'Language & Communication'), ('cognitive', 'Cognitive')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('typical_age_months', models.PositiveIntegerField(help_text='Typical age when achieved')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['typical_age_months', 'category'],
            },
        ),
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age_in_months', models.PositiveIntegerField(help_text='Age when vaccine should be given')),
                ('dose_number', models.PositiveIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('protects_against', models.CharField(blank=True, max_length=200)),
                ('side_effects', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vaccine Schedule',
                'verbose_name_plural': 'Vaccine Schedules',
                'ordering': ['age_in_months', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Birth weight in kg', max_digits=4, null=True)),
                ('birth_height', models.DecimalField(blank=True, decimal_places=2, help_text='Birth height in cm', max_digits=5, null=True)),
                ('blood_group', models.CharField(blank=True, help_text='e.g., O+, A-, AB+', max_length=5)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies, separated by commas')),
                ('medical_conditions', models.TextField(blank=True, help_text='Any chronic conditions')),
                ('photo', models.ImageField(blank=True, upload_to='child_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(help_text='e.g., Pediatrician, Grandparent', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='child_tracker.child')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, help_text='Head circumference in cm (for infants)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('measured_by', models.CharField(blank=True, max_length=100)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='child_tracker.child')),
            ],
            options={
                'verbose_name': 'Growth Record',
                'verbose_name_plural': 'Growth Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 5ml, 250mg', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice daily, Every 6 hours', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prescribed_for', models.CharField(help_text='Condition/Symptom', max_length=200)),
                ('prescribed_by', models.CharField(blank=True, help_text='Doctor name', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions')),
                ('side_effects_observed', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='child_tracker.child')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_records', to='child_tracker.child')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_tracker.milestone')),
            ],
            options={
                'verbose_name': 'Milestone Record',
                'verbose_name_plural': 'Milestone Records',
                'ordering': ['milestone__typical_age_months'],
                'unique_together': {('child', 'milestone')},
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, help_text='Doctor/Clinic name', max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_overdue', models.BooleanField(default=False)),
                ('had_reaction', models.BooleanField(default=False)),
                ('reaction_details', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='child_tracker.child')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_tracker.vaccineschedule')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'ordering': ['vaccine__age_in_months'],
                'unique_together': {('child', 'vaccine')},
            },
        ),
    ]
