# Generated by Django 6.0.2 on 2026-02-09 20:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('file', models.FileField(help_text='Upload photo or video (max 10MB for videos)', upload_to='child_memories/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='child_memories/thumbnails/')),
                ('title', models.CharField(blank=True, help_text='e.g., First Steps, Birthday Party', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Capture the moment')),
                ('memory_date', models.DateField(default=datetime.date.today, help_text='When was this moment?')),
                ('child_age_months', models.PositiveIntegerField(blank=True, help_text='Auto-calculated', null=True)),
                ('is_milestone', models.BooleanField(default=False, help_text='Is this a milestone moment?')),
                ('tags', models.CharField(blank=True, help_text='Tags separated by commas', max_length=200)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='child_tracker.child')),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
                'ordering': ['-memory_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
